import DevNotesCore
import XCTest

final class NoteIDTests: XCTestCase {
    func testHidesAutoGeneratedUUIDFileNames() {
        let id = NoteID("\(UUID().uuidString).md")
        XCTAssertNil(id.displayFileName)
    }

    func testKeepsHumanNamedFiles() {
        XCTAssertEqual(NoteID("Inbox.md").displayFileName, "Inbox.md")
        XCTAssertEqual(NoteID("2026-07-24 standup.md").displayFileName, "2026-07-24 standup.md")
    }

    func testKeepsNamesThatMerelyLookLongButAreNotUUIDs() {
        let name = "a-very-long-note-name-that-is-not-a-uuid-at-all.md"
        XCTAssertEqual(NoteID(name).displayFileName, name)
    }
}
